server:
  host: 127.0.0.1
  port: 9090
  readTimeout: 30000
  writeTimeout: 30000
  shutdownTimeOut: 10000
  connectTimeOut: 30000

postgres:
  host: 127.0.0.1
  port: 5432
  userName: postgres
  password: root
  database: health

authorization:
  secretKey: 'b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9'
  expireTime: 86400